name: Docker Build
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        php_version: [7.4, 8.1]
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build And Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: bzrk/php-cli:${{ matrix.php_version }}
          file: DockerfilePHP
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}-cli
